// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package email

import (
	"github.com/compendium-tech/compendium/email-delivery-service/pkg/email"
	mock "github.com/stretchr/testify/mock"
)

// NewMockEmailMessageBuilder creates a new instance of MockEmailMessageBuilder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEmailMessageBuilder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEmailMessageBuilder {
	mock := &MockEmailMessageBuilder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEmailMessageBuilder is an autogenerated mock type for the EmailMessageBuilder type
type MockEmailMessageBuilder struct {
	mock.Mock
}

type MockEmailMessageBuilder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEmailMessageBuilder) EXPECT() *MockEmailMessageBuilder_Expecter {
	return &MockEmailMessageBuilder_Expecter{mock: &_m.Mock}
}

// BuildPasswordResetMfaEmailMessage provides a mock function for the type MockEmailMessageBuilder
func (_mock *MockEmailMessageBuilder) BuildPasswordResetMfaEmailMessage(to string, otp string) (email.EmailMessage, error) {
	ret := _mock.Called(to, otp)

	if len(ret) == 0 {
		panic("no return value specified for BuildPasswordResetMfaEmailMessage")
	}

	var r0 email.EmailMessage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (email.EmailMessage, error)); ok {
		return returnFunc(to, otp)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) email.EmailMessage); ok {
		r0 = returnFunc(to, otp)
	} else {
		r0 = ret.Get(0).(email.EmailMessage)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(to, otp)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEmailMessageBuilder_BuildPasswordResetMfaEmailMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BuildPasswordResetMfaEmailMessage'
type MockEmailMessageBuilder_BuildPasswordResetMfaEmailMessage_Call struct {
	*mock.Call
}

// BuildPasswordResetMfaEmailMessage is a helper method to define mock.On call
//   - to string
//   - otp string
func (_e *MockEmailMessageBuilder_Expecter) BuildPasswordResetMfaEmailMessage(to interface{}, otp interface{}) *MockEmailMessageBuilder_BuildPasswordResetMfaEmailMessage_Call {
	return &MockEmailMessageBuilder_BuildPasswordResetMfaEmailMessage_Call{Call: _e.mock.On("BuildPasswordResetMfaEmailMessage", to, otp)}
}

func (_c *MockEmailMessageBuilder_BuildPasswordResetMfaEmailMessage_Call) Run(run func(to string, otp string)) *MockEmailMessageBuilder_BuildPasswordResetMfaEmailMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEmailMessageBuilder_BuildPasswordResetMfaEmailMessage_Call) Return(emailMessage email.EmailMessage, err error) *MockEmailMessageBuilder_BuildPasswordResetMfaEmailMessage_Call {
	_c.Call.Return(emailMessage, err)
	return _c
}

func (_c *MockEmailMessageBuilder_BuildPasswordResetMfaEmailMessage_Call) RunAndReturn(run func(to string, otp string) (email.EmailMessage, error)) *MockEmailMessageBuilder_BuildPasswordResetMfaEmailMessage_Call {
	_c.Call.Return(run)
	return _c
}

// BuildSignInMfaEmailMessage provides a mock function for the type MockEmailMessageBuilder
func (_mock *MockEmailMessageBuilder) BuildSignInMfaEmailMessage(to string, otp string) (email.EmailMessage, error) {
	ret := _mock.Called(to, otp)

	if len(ret) == 0 {
		panic("no return value specified for BuildSignInMfaEmailMessage")
	}

	var r0 email.EmailMessage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (email.EmailMessage, error)); ok {
		return returnFunc(to, otp)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) email.EmailMessage); ok {
		r0 = returnFunc(to, otp)
	} else {
		r0 = ret.Get(0).(email.EmailMessage)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(to, otp)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEmailMessageBuilder_BuildSignInMfaEmailMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BuildSignInMfaEmailMessage'
type MockEmailMessageBuilder_BuildSignInMfaEmailMessage_Call struct {
	*mock.Call
}

// BuildSignInMfaEmailMessage is a helper method to define mock.On call
//   - to string
//   - otp string
func (_e *MockEmailMessageBuilder_Expecter) BuildSignInMfaEmailMessage(to interface{}, otp interface{}) *MockEmailMessageBuilder_BuildSignInMfaEmailMessage_Call {
	return &MockEmailMessageBuilder_BuildSignInMfaEmailMessage_Call{Call: _e.mock.On("BuildSignInMfaEmailMessage", to, otp)}
}

func (_c *MockEmailMessageBuilder_BuildSignInMfaEmailMessage_Call) Run(run func(to string, otp string)) *MockEmailMessageBuilder_BuildSignInMfaEmailMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEmailMessageBuilder_BuildSignInMfaEmailMessage_Call) Return(emailMessage email.EmailMessage, err error) *MockEmailMessageBuilder_BuildSignInMfaEmailMessage_Call {
	_c.Call.Return(emailMessage, err)
	return _c
}

func (_c *MockEmailMessageBuilder_BuildSignInMfaEmailMessage_Call) RunAndReturn(run func(to string, otp string) (email.EmailMessage, error)) *MockEmailMessageBuilder_BuildSignInMfaEmailMessage_Call {
	_c.Call.Return(run)
	return _c
}

// BuildSignUpMfaEmailMessage provides a mock function for the type MockEmailMessageBuilder
func (_mock *MockEmailMessageBuilder) BuildSignUpMfaEmailMessage(to string, otp string) (email.EmailMessage, error) {
	ret := _mock.Called(to, otp)

	if len(ret) == 0 {
		panic("no return value specified for BuildSignUpMfaEmailMessage")
	}

	var r0 email.EmailMessage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (email.EmailMessage, error)); ok {
		return returnFunc(to, otp)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) email.EmailMessage); ok {
		r0 = returnFunc(to, otp)
	} else {
		r0 = ret.Get(0).(email.EmailMessage)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(to, otp)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEmailMessageBuilder_BuildSignUpMfaEmailMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BuildSignUpMfaEmailMessage'
type MockEmailMessageBuilder_BuildSignUpMfaEmailMessage_Call struct {
	*mock.Call
}

// BuildSignUpMfaEmailMessage is a helper method to define mock.On call
//   - to string
//   - otp string
func (_e *MockEmailMessageBuilder_Expecter) BuildSignUpMfaEmailMessage(to interface{}, otp interface{}) *MockEmailMessageBuilder_BuildSignUpMfaEmailMessage_Call {
	return &MockEmailMessageBuilder_BuildSignUpMfaEmailMessage_Call{Call: _e.mock.On("BuildSignUpMfaEmailMessage", to, otp)}
}

func (_c *MockEmailMessageBuilder_BuildSignUpMfaEmailMessage_Call) Run(run func(to string, otp string)) *MockEmailMessageBuilder_BuildSignUpMfaEmailMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEmailMessageBuilder_BuildSignUpMfaEmailMessage_Call) Return(emailMessage email.EmailMessage, err error) *MockEmailMessageBuilder_BuildSignUpMfaEmailMessage_Call {
	_c.Call.Return(emailMessage, err)
	return _c
}

func (_c *MockEmailMessageBuilder_BuildSignUpMfaEmailMessage_Call) RunAndReturn(run func(to string, otp string) (email.EmailMessage, error)) *MockEmailMessageBuilder_BuildSignUpMfaEmailMessage_Call {
	_c.Call.Return(run)
	return _c
}
