// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.32.0
// source: college-service/proto/subscription_service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubscriptionTier int32

const (
	SubscriptionTier_NONE      SubscriptionTier = 0
	SubscriptionTier_STUDENT   SubscriptionTier = 1
	SubscriptionTier_TEAM      SubscriptionTier = 2
	SubscriptionTier_COMMUNITY SubscriptionTier = 3
)

// Enum value maps for SubscriptionTier.
var (
	SubscriptionTier_name = map[int32]string{
		0: "NONE",
		1: "STUDENT",
		2: "TEAM",
		3: "COMMUNITY",
	}
	SubscriptionTier_value = map[string]int32{
		"NONE":      0,
		"STUDENT":   1,
		"TEAM":      2,
		"COMMUNITY": 3,
	}
)

func (x SubscriptionTier) Enum() *SubscriptionTier {
	p := new(SubscriptionTier)
	*p = x
	return p
}

func (x SubscriptionTier) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SubscriptionTier) Descriptor() protoreflect.EnumDescriptor {
	return file_college_service_proto_subscription_service_proto_enumTypes[0].Descriptor()
}

func (SubscriptionTier) Type() protoreflect.EnumType {
	return &file_college_service_proto_subscription_service_proto_enumTypes[0]
}

func (x SubscriptionTier) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SubscriptionTier.Descriptor instead.
func (SubscriptionTier) EnumDescriptor() ([]byte, []int) {
	return file_college_service_proto_subscription_service_proto_rawDescGZIP(), []int{0}
}

type GetSubscriptionTierRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubscriptionTierRequest) Reset() {
	*x = GetSubscriptionTierRequest{}
	mi := &file_college_service_proto_subscription_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubscriptionTierRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubscriptionTierRequest) ProtoMessage() {}

func (x *GetSubscriptionTierRequest) ProtoReflect() protoreflect.Message {
	mi := &file_college_service_proto_subscription_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubscriptionTierRequest.ProtoReflect.Descriptor instead.
func (*GetSubscriptionTierRequest) Descriptor() ([]byte, []int) {
	return file_college_service_proto_subscription_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetSubscriptionTierRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetSubscriptionTierResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tier          SubscriptionTier       `protobuf:"varint,1,opt,name=tier,proto3,enum=subscription_service.v1.SubscriptionTier" json:"tier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubscriptionTierResponse) Reset() {
	*x = GetSubscriptionTierResponse{}
	mi := &file_college_service_proto_subscription_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubscriptionTierResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubscriptionTierResponse) ProtoMessage() {}

func (x *GetSubscriptionTierResponse) ProtoReflect() protoreflect.Message {
	mi := &file_college_service_proto_subscription_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubscriptionTierResponse.ProtoReflect.Descriptor instead.
func (*GetSubscriptionTierResponse) Descriptor() ([]byte, []int) {
	return file_college_service_proto_subscription_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetSubscriptionTierResponse) GetTier() SubscriptionTier {
	if x != nil {
		return x.Tier
	}
	return SubscriptionTier_NONE
}

var File_college_service_proto_subscription_service_proto protoreflect.FileDescriptor

const file_college_service_proto_subscription_service_proto_rawDesc = "" +
	"\n" +
	"0college-service/proto/subscription_service.proto\x12\x17subscription_service.v1\"4\n" +
	"\x1aGetSubscriptionTierRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\"\\\n" +
	"\x1bGetSubscriptionTierResponse\x12=\n" +
	"\x04tier\x18\x01 \x01(\x0e2).subscription_service.v1.SubscriptionTierR\x04tier*B\n" +
	"\x10SubscriptionTier\x12\b\n" +
	"\x04NONE\x10\x00\x12\v\n" +
	"\aSTUDENT\x10\x01\x12\b\n" +
	"\x04TEAM\x10\x02\x12\r\n" +
	"\tCOMMUNITY\x10\x032\x98\x01\n" +
	"\x13SubscriptionService\x12\x80\x01\n" +
	"\x13GetSubscriptionTier\x123.subscription_service.v1.GetSubscriptionTierRequest\x1a4.subscription_service.v1.GetSubscriptionTierResponseB\x13Z\x11internal/proto/v1b\x06proto3"

var (
	file_college_service_proto_subscription_service_proto_rawDescOnce sync.Once
	file_college_service_proto_subscription_service_proto_rawDescData []byte
)

func file_college_service_proto_subscription_service_proto_rawDescGZIP() []byte {
	file_college_service_proto_subscription_service_proto_rawDescOnce.Do(func() {
		file_college_service_proto_subscription_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_college_service_proto_subscription_service_proto_rawDesc), len(file_college_service_proto_subscription_service_proto_rawDesc)))
	})
	return file_college_service_proto_subscription_service_proto_rawDescData
}

var file_college_service_proto_subscription_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_college_service_proto_subscription_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_college_service_proto_subscription_service_proto_goTypes = []any{
	(SubscriptionTier)(0),               // 0: subscription_service.v1.SubscriptionTier
	(*GetSubscriptionTierRequest)(nil),  // 1: subscription_service.v1.GetSubscriptionTierRequest
	(*GetSubscriptionTierResponse)(nil), // 2: subscription_service.v1.GetSubscriptionTierResponse
}
var file_college_service_proto_subscription_service_proto_depIdxs = []int32{
	0, // 0: subscription_service.v1.GetSubscriptionTierResponse.tier:type_name -> subscription_service.v1.SubscriptionTier
	1, // 1: subscription_service.v1.SubscriptionService.GetSubscriptionTier:input_type -> subscription_service.v1.GetSubscriptionTierRequest
	2, // 2: subscription_service.v1.SubscriptionService.GetSubscriptionTier:output_type -> subscription_service.v1.GetSubscriptionTierResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_college_service_proto_subscription_service_proto_init() }
func file_college_service_proto_subscription_service_proto_init() {
	if File_college_service_proto_subscription_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_college_service_proto_subscription_service_proto_rawDesc), len(file_college_service_proto_subscription_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_college_service_proto_subscription_service_proto_goTypes,
		DependencyIndexes: file_college_service_proto_subscription_service_proto_depIdxs,
		EnumInfos:         file_college_service_proto_subscription_service_proto_enumTypes,
		MessageInfos:      file_college_service_proto_subscription_service_proto_msgTypes,
	}.Build()
	File_college_service_proto_subscription_service_proto = out.File
	file_college_service_proto_subscription_service_proto_goTypes = nil
	file_college_service_proto_subscription_service_proto_depIdxs = nil
}
