// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package geoip

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockGeoIp creates a new instance of MockGeoIp. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGeoIp(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGeoIp {
	mock := &MockGeoIp{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGeoIp is an autogenerated mock type for the GeoIp type
type MockGeoIp struct {
	mock.Mock
}

type MockGeoIp_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGeoIp) EXPECT() *MockGeoIp_Expecter {
	return &MockGeoIp_Expecter{mock: &_m.Mock}
}

// GetLocation provides a mock function for the type MockGeoIp
func (_mock *MockGeoIp) GetLocation(ip string) (string, error) {
	ret := _mock.Called(ip)

	if len(ret) == 0 {
		panic("no return value specified for GetLocation")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(ip)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(ip)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(ip)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGeoIp_GetLocation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLocation'
type MockGeoIp_GetLocation_Call struct {
	*mock.Call
}

// GetLocation is a helper method to define mock.On call
//   - ip string
func (_e *MockGeoIp_Expecter) GetLocation(ip interface{}) *MockGeoIp_GetLocation_Call {
	return &MockGeoIp_GetLocation_Call{Call: _e.mock.On("GetLocation", ip)}
}

func (_c *MockGeoIp_GetLocation_Call) Run(run func(ip string)) *MockGeoIp_GetLocation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockGeoIp_GetLocation_Call) Return(s string, err error) *MockGeoIp_GetLocation_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockGeoIp_GetLocation_Call) RunAndReturn(run func(ip string) (string, error)) *MockGeoIp_GetLocation_Call {
	_c.Call.Return(run)
	return _c
}
