// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/assistant_service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message_Role int32

const (
	Message_SYSTEM    Message_Role = 0
	Message_USER      Message_Role = 1
	Message_ASSISTANT Message_Role = 2
	Message_TOOL      Message_Role = 3
)

// Enum value maps for Message_Role.
var (
	Message_Role_name = map[int32]string{
		0: "SYSTEM",
		1: "USER",
		2: "ASSISTANT",
		3: "TOOL",
	}
	Message_Role_value = map[string]int32{
		"SYSTEM":    0,
		"USER":      1,
		"ASSISTANT": 2,
		"TOOL":      3,
	}
)

func (x Message_Role) Enum() *Message_Role {
	p := new(Message_Role)
	*p = x
	return p
}

func (x Message_Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Message_Role) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_assistant_service_proto_enumTypes[0].Descriptor()
}

func (Message_Role) Type() protoreflect.EnumType {
	return &file_proto_assistant_service_proto_enumTypes[0]
}

func (x Message_Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Message_Role.Descriptor instead.
func (Message_Role) EnumDescriptor() ([]byte, []int) {
	return file_proto_assistant_service_proto_rawDescGZIP(), []int{4, 0}
}

type ToolParameterDefinition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	IsRequired    bool                   `protobuf:"varint,4,opt,name=is_required,json=isRequired,proto3" json:"is_required,omitempty"`
	Enum          []string               `protobuf:"bytes,5,rep,name=enum,proto3" json:"enum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolParameterDefinition) Reset() {
	*x = ToolParameterDefinition{}
	mi := &file_proto_assistant_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolParameterDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolParameterDefinition) ProtoMessage() {}

func (x *ToolParameterDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_proto_assistant_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolParameterDefinition.ProtoReflect.Descriptor instead.
func (*ToolParameterDefinition) Descriptor() ([]byte, []int) {
	return file_proto_assistant_service_proto_rawDescGZIP(), []int{0}
}

func (x *ToolParameterDefinition) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ToolParameterDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolParameterDefinition) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ToolParameterDefinition) GetIsRequired() bool {
	if x != nil {
		return x.IsRequired
	}
	return false
}

func (x *ToolParameterDefinition) GetEnum() []string {
	if x != nil {
		return x.Enum
	}
	return nil
}

type ToolDefinition struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Name          string                     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                     `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Parameters    []*ToolParameterDefinition `protobuf:"bytes,3,rep,name=parameters,proto3" json:"parameters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolDefinition) Reset() {
	*x = ToolDefinition{}
	mi := &file_proto_assistant_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolDefinition) ProtoMessage() {}

func (x *ToolDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_proto_assistant_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolDefinition.ProtoReflect.Descriptor instead.
func (*ToolDefinition) Descriptor() ([]byte, []int) {
	return file_proto_assistant_service_proto_rawDescGZIP(), []int{1}
}

func (x *ToolDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolDefinition) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ToolDefinition) GetParameters() []*ToolParameterDefinition {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type ToolCall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Parameters    []*ToolCallParameter   `protobuf:"bytes,3,rep,name=parameters,proto3" json:"parameters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCall) Reset() {
	*x = ToolCall{}
	mi := &file_proto_assistant_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCall) ProtoMessage() {}

func (x *ToolCall) ProtoReflect() protoreflect.Message {
	mi := &file_proto_assistant_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCall.ProtoReflect.Descriptor instead.
func (*ToolCall) Descriptor() ([]byte, []int) {
	return file_proto_assistant_service_proto_rawDescGZIP(), []int{2}
}

func (x *ToolCall) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ToolCall) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolCall) GetParameters() []*ToolCallParameter {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type ToolCallParameter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         *anypb.Any             `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCallParameter) Reset() {
	*x = ToolCallParameter{}
	mi := &file_proto_assistant_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCallParameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCallParameter) ProtoMessage() {}

func (x *ToolCallParameter) ProtoReflect() protoreflect.Message {
	mi := &file_proto_assistant_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCallParameter.ProtoReflect.Descriptor instead.
func (*ToolCallParameter) Descriptor() ([]byte, []int) {
	return file_proto_assistant_service_proto_rawDescGZIP(), []int{3}
}

func (x *ToolCallParameter) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolCallParameter) GetValue() *anypb.Any {
	if x != nil {
		return x.Value
	}
	return nil
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          Message_Role           `protobuf:"varint,1,opt,name=role,proto3,enum=assistant_service.v1.Message_Role" json:"role,omitempty"`
	TextContent   string                 `protobuf:"bytes,2,opt,name=text_content,json=textContent,proto3" json:"text_content,omitempty"`
	ToolCalls     []*ToolCall            `protobuf:"bytes,3,rep,name=tool_calls,json=toolCalls,proto3" json:"tool_calls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_proto_assistant_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_proto_assistant_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_proto_assistant_service_proto_rawDescGZIP(), []int{4}
}

func (x *Message) GetRole() Message_Role {
	if x != nil {
		return x.Role
	}
	return Message_SYSTEM
}

func (x *Message) GetTextContent() string {
	if x != nil {
		return x.TextContent
	}
	return ""
}

func (x *Message) GetToolCalls() []*ToolCall {
	if x != nil {
		return x.ToolCalls
	}
	return nil
}

type CreateResponseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	Tools         []*ToolDefinition      `protobuf:"bytes,2,rep,name=tools,proto3" json:"tools,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResponseRequest) Reset() {
	*x = CreateResponseRequest{}
	mi := &file_proto_assistant_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponseRequest) ProtoMessage() {}

func (x *CreateResponseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_assistant_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponseRequest.ProtoReflect.Descriptor instead.
func (*CreateResponseRequest) Descriptor() ([]byte, []int) {
	return file_proto_assistant_service_proto_rawDescGZIP(), []int{5}
}

func (x *CreateResponseRequest) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *CreateResponseRequest) GetTools() []*ToolDefinition {
	if x != nil {
		return x.Tools
	}
	return nil
}

type CreateResponseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *Message               `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResponseResponse) Reset() {
	*x = CreateResponseResponse{}
	mi := &file_proto_assistant_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponseResponse) ProtoMessage() {}

func (x *CreateResponseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_assistant_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponseResponse.ProtoReflect.Descriptor instead.
func (*CreateResponseResponse) Descriptor() ([]byte, []int) {
	return file_proto_assistant_service_proto_rawDescGZIP(), []int{6}
}

func (x *CreateResponseResponse) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

var File_proto_assistant_service_proto protoreflect.FileDescriptor

const file_proto_assistant_service_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/assistant_service.proto\x12\x14assistant_service.v1\x1a\x19google/protobuf/any.proto\"\x98\x01\n" +
	"\x17ToolParameterDefinition\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1f\n" +
	"\vis_required\x18\x04 \x01(\bR\n" +
	"isRequired\x12\x12\n" +
	"\x04enum\x18\x05 \x03(\tR\x04enum\"\x95\x01\n" +
	"\x0eToolDefinition\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12M\n" +
	"\n" +
	"parameters\x18\x03 \x03(\v2-.assistant_service.v1.ToolParameterDefinitionR\n" +
	"parameters\"w\n" +
	"\bToolCall\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12G\n" +
	"\n" +
	"parameters\x18\x03 \x03(\v2'.assistant_service.v1.ToolCallParameterR\n" +
	"parameters\"S\n" +
	"\x11ToolCallParameter\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\x05value\"\xda\x01\n" +
	"\aMessage\x126\n" +
	"\x04role\x18\x01 \x01(\x0e2\".assistant_service.v1.Message.RoleR\x04role\x12!\n" +
	"\ftext_content\x18\x02 \x01(\tR\vtextContent\x12=\n" +
	"\n" +
	"tool_calls\x18\x03 \x03(\v2\x1e.assistant_service.v1.ToolCallR\ttoolCalls\"5\n" +
	"\x04Role\x12\n" +
	"\n" +
	"\x06SYSTEM\x10\x00\x12\b\n" +
	"\x04USER\x10\x01\x12\r\n" +
	"\tASSISTANT\x10\x02\x12\b\n" +
	"\x04TOOL\x10\x03\"\x8e\x01\n" +
	"\x15CreateResponseRequest\x129\n" +
	"\bmessages\x18\x01 \x03(\v2\x1d.assistant_service.v1.MessageR\bmessages\x12:\n" +
	"\x05tools\x18\x02 \x03(\v2$.assistant_service.v1.ToolDefinitionR\x05tools\"Q\n" +
	"\x16CreateResponseResponse\x127\n" +
	"\amessage\x18\x01 \x01(\v2\x1d.assistant_service.v1.MessageR\amessage2\x7f\n" +
	"\x10AssistantService\x12k\n" +
	"\x0eCreateResponse\x12+.assistant_service.v1.CreateResponseRequest\x1a,.assistant_service.v1.CreateResponseResponseB\x13Z\x11internal/proto/v1b\x06proto3"

var (
	file_proto_assistant_service_proto_rawDescOnce sync.Once
	file_proto_assistant_service_proto_rawDescData []byte
)

func file_proto_assistant_service_proto_rawDescGZIP() []byte {
	file_proto_assistant_service_proto_rawDescOnce.Do(func() {
		file_proto_assistant_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_assistant_service_proto_rawDesc), len(file_proto_assistant_service_proto_rawDesc)))
	})
	return file_proto_assistant_service_proto_rawDescData
}

var file_proto_assistant_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_assistant_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_assistant_service_proto_goTypes = []any{
	(Message_Role)(0),               // 0: assistant_service.v1.Message.Role
	(*ToolParameterDefinition)(nil), // 1: assistant_service.v1.ToolParameterDefinition
	(*ToolDefinition)(nil),          // 2: assistant_service.v1.ToolDefinition
	(*ToolCall)(nil),                // 3: assistant_service.v1.ToolCall
	(*ToolCallParameter)(nil),       // 4: assistant_service.v1.ToolCallParameter
	(*Message)(nil),                 // 5: assistant_service.v1.Message
	(*CreateResponseRequest)(nil),   // 6: assistant_service.v1.CreateResponseRequest
	(*CreateResponseResponse)(nil),  // 7: assistant_service.v1.CreateResponseResponse
	(*anypb.Any)(nil),               // 8: google.protobuf.Any
}
var file_proto_assistant_service_proto_depIdxs = []int32{
	1, // 0: assistant_service.v1.ToolDefinition.parameters:type_name -> assistant_service.v1.ToolParameterDefinition
	4, // 1: assistant_service.v1.ToolCall.parameters:type_name -> assistant_service.v1.ToolCallParameter
	8, // 2: assistant_service.v1.ToolCallParameter.value:type_name -> google.protobuf.Any
	0, // 3: assistant_service.v1.Message.role:type_name -> assistant_service.v1.Message.Role
	3, // 4: assistant_service.v1.Message.tool_calls:type_name -> assistant_service.v1.ToolCall
	5, // 5: assistant_service.v1.CreateResponseRequest.messages:type_name -> assistant_service.v1.Message
	2, // 6: assistant_service.v1.CreateResponseRequest.tools:type_name -> assistant_service.v1.ToolDefinition
	5, // 7: assistant_service.v1.CreateResponseResponse.message:type_name -> assistant_service.v1.Message
	6, // 8: assistant_service.v1.AssistantService.CreateResponse:input_type -> assistant_service.v1.CreateResponseRequest
	7, // 9: assistant_service.v1.AssistantService.CreateResponse:output_type -> assistant_service.v1.CreateResponseResponse
	9, // [9:10] is the sub-list for method output_type
	8, // [8:9] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_proto_assistant_service_proto_init() }
func file_proto_assistant_service_proto_init() {
	if File_proto_assistant_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_assistant_service_proto_rawDesc), len(file_proto_assistant_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_assistant_service_proto_goTypes,
		DependencyIndexes: file_proto_assistant_service_proto_depIdxs,
		EnumInfos:         file_proto_assistant_service_proto_enumTypes,
		MessageInfos:      file_proto_assistant_service_proto_msgTypes,
	}.Build()
	File_proto_assistant_service_proto = out.File
	file_proto_assistant_service_proto_goTypes = nil
	file_proto_assistant_service_proto_depIdxs = nil
}
